# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alyosha/work/git/mesoscopic-functional-connectivity/codes/moviemaker/moviemakerapp.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MovieMakerApp(object):
    def setupUi(self, MovieMakerApp):
        MovieMakerApp.setObjectName("MovieMakerApp")
        MovieMakerApp.resize(1400, 1085)
        self.centralWidget = QtWidgets.QWidget(MovieMakerApp)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fcDataComboBox = QtWidgets.QComboBox(self.centralWidget)
        self.fcDataComboBox.setObjectName("fcDataComboBox")
        self.verticalLayout_2.addWidget(self.fcDataComboBox)
        self.channelTableWidget = QtWidgets.QTableWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelTableWidget.sizePolicy().hasHeightForWidth())
        self.channelTableWidget.setSizePolicy(sizePolicy)
        self.channelTableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.channelTableWidget.setObjectName("channelTableWidget")
        self.channelTableWidget.setColumnCount(3)
        self.channelTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.channelTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.channelTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.channelTableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.channelTableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.movieFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieFrame.sizePolicy().hasHeightForWidth())
        self.movieFrame.setSizePolicy(sizePolicy)
        self.movieFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.movieFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.movieFrame.setObjectName("movieFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.movieFrame)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.movieFrameLayout = QtWidgets.QVBoxLayout()
        self.movieFrameLayout.setSpacing(6)
        self.movieFrameLayout.setObjectName("movieFrameLayout")
        self.verticalLayout_6.addLayout(self.movieFrameLayout)
        self.verticalLayout.addWidget(self.movieFrame)
        self.movieControlsLayout = QtWidgets.QHBoxLayout()
        self.movieControlsLayout.setSpacing(6)
        self.movieControlsLayout.setObjectName("movieControlsLayout")
        self.movieFrameSlider = QtWidgets.QSlider(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieFrameSlider.sizePolicy().hasHeightForWidth())
        self.movieFrameSlider.setSizePolicy(sizePolicy)
        self.movieFrameSlider.setMaximum(200)
        self.movieFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.movieFrameSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.movieFrameSlider.setTickInterval(10)
        self.movieFrameSlider.setObjectName("movieFrameSlider")
        self.movieControlsLayout.addWidget(self.movieFrameSlider)
        self.movieFrameLabel = QtWidgets.QLabel(self.centralWidget)
        self.movieFrameLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.movieFrameLabel.setObjectName("movieFrameLabel")
        self.movieControlsLayout.addWidget(self.movieFrameLabel)
        self.verticalLayout.addLayout(self.movieControlsLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MovieMakerApp.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MovieMakerApp)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1400, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MovieMakerApp.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MovieMakerApp)
        self.statusBar.setObjectName("statusBar")
        MovieMakerApp.setStatusBar(self.statusBar)
        self.actionLoad_Data_Folder = QtWidgets.QAction(MovieMakerApp)
        self.actionLoad_Data_Folder.setObjectName("actionLoad_Data_Folder")
        self.actionLoad_FC_File = QtWidgets.QAction(MovieMakerApp)
        self.actionLoad_FC_File.setObjectName("actionLoad_FC_File")
        self.actionLoad_node_layout = QtWidgets.QAction(MovieMakerApp)
        self.actionLoad_node_layout.setObjectName("actionLoad_node_layout")
        self.actionExport_movie = QtWidgets.QAction(MovieMakerApp)
        self.actionExport_movie.setObjectName("actionExport_movie")
        self.actionSave_node_layout = QtWidgets.QAction(MovieMakerApp)
        self.actionSave_node_layout.setObjectName("actionSave_node_layout")
        self.actionExit = QtWidgets.QAction(MovieMakerApp)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_Recent = QtWidgets.QAction(MovieMakerApp)
        self.actionLoad_Recent.setObjectName("actionLoad_Recent")
        self.actionUpdate_Plot = QtWidgets.QAction(MovieMakerApp)
        self.actionUpdate_Plot.setObjectName("actionUpdate_Plot")
        self.actionAutogen_Circles = QtWidgets.QAction(MovieMakerApp)
        self.actionAutogen_Circles.setObjectName("actionAutogen_Circles")
        self.actionLabel_Nodes = QtWidgets.QAction(MovieMakerApp)
        self.actionLabel_Nodes.setCheckable(True)
        self.actionLabel_Nodes.setObjectName("actionLabel_Nodes")
        self.actionActivity_Based_Nodes = QtWidgets.QAction(MovieMakerApp)
        self.actionActivity_Based_Nodes.setCheckable(True)
        self.actionActivity_Based_Nodes.setObjectName("actionActivity_Based_Nodes")
        self.actionUndirected_Edges = QtWidgets.QAction(MovieMakerApp)
        self.actionUndirected_Edges.setCheckable(True)
        self.actionUndirected_Edges.setObjectName("actionUndirected_Edges")
        self.actionFC_Based_Edges = QtWidgets.QAction(MovieMakerApp)
        self.actionFC_Based_Edges.setCheckable(True)
        self.actionFC_Based_Edges.setObjectName("actionFC_Based_Edges")
        self.menuFile.addAction(self.actionLoad_Data_Folder)
        self.menuFile.addAction(self.actionLoad_FC_File)
        self.menuFile.addAction(self.actionLoad_node_layout)
        self.menuFile.addAction(self.actionLoad_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_movie)
        self.menuFile.addAction(self.actionSave_node_layout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUpdate_Plot)
        self.menuEdit.addAction(self.actionAutogen_Circles)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionLabel_Nodes)
        self.menuEdit.addAction(self.actionActivity_Based_Nodes)
        self.menuEdit.addAction(self.actionUndirected_Edges)
        self.menuEdit.addAction(self.actionFC_Based_Edges)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MovieMakerApp)
        QtCore.QMetaObject.connectSlotsByName(MovieMakerApp)

    def retranslateUi(self, MovieMakerApp):
        _translate = QtCore.QCoreApplication.translate
        MovieMakerApp.setWindowTitle(_translate("MovieMakerApp", "MovieMakerApp"))
        self.channelTableWidget.setSortingEnabled(True)
        item = self.channelTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MovieMakerApp", "use"))
        item = self.channelTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MovieMakerApp", "idx"))
        item = self.channelTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MovieMakerApp", "label"))
        self.movieFrameLabel.setText(_translate("MovieMakerApp", "0"))
        self.menuFile.setTitle(_translate("MovieMakerApp", "File"))
        self.menuEdit.setTitle(_translate("MovieMakerApp", "Edit"))
        self.actionLoad_Data_Folder.setText(_translate("MovieMakerApp", "Load data folder..."))
        self.actionLoad_FC_File.setText(_translate("MovieMakerApp", "Load FC file..."))
        self.actionLoad_node_layout.setText(_translate("MovieMakerApp", "Load node layout..."))
        self.actionExport_movie.setText(_translate("MovieMakerApp", "Export movie..."))
        self.actionSave_node_layout.setText(_translate("MovieMakerApp", "Save node layout..."))
        self.actionExit.setText(_translate("MovieMakerApp", "Exit..."))
        self.actionLoad_Recent.setText(_translate("MovieMakerApp", "Load Recent"))
        self.actionUpdate_Plot.setText(_translate("MovieMakerApp", "Update Plot"))
        self.actionAutogen_Circles.setText(_translate("MovieMakerApp", "Autogen Circles"))
        self.actionLabel_Nodes.setText(_translate("MovieMakerApp", "Label Nodes"))
        self.actionActivity_Based_Nodes.setText(_translate("MovieMakerApp", "Activity-Based Nodes"))
        self.actionUndirected_Edges.setText(_translate("MovieMakerApp", "Undirected Edges"))
        self.actionFC_Based_Edges.setText(_translate("MovieMakerApp", "FC-Based Edges"))
